### ISSUE TITLE
Headers installed in non-standard location

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/ncurses-feedstock#3] opened 2016-04-15 19:22 UTC
Typically header files are installed in $PREFIX/include but in this package the header files are installed into $PREFIX/include/ncursesw.  Is there a compelling reason for this?

**Comment by jjhelmus** [comment] 2016-04-15 19:28
Actually this looks to be the case for the ncurses 5.9-5 package in the default channel ($PREFIX/include/ncurses) so this likely is intentional.

**Comment by pelson** [comment] 2016-04-16 08:08
It isn't something we've configured. That is the default behaviour from ncurses. Most packages which depend on ncurses will be expecting this behaviour, so I don't think we should change it unless we have a compelling reason to.

@jjhelmus - if you are happy to, I think we can close this issue?

**Comment by jjhelmus** [comment] 2016-04-16 12:36
It looks like the `--includedir` flag can be used to set the location where the include files are installed.  The [ncurses Debain package is setting this to `${prefix}/include`](https://anonscm.debian.org/cgit/collab-maint/ncurses.git/tree/package/ncurses.spec#n41) to not create the sub-directory.  Would it be reasonable for the conda package to do the same?

**Comment by jakirkham** [comment] 2016-04-16 17:09
In CentOS 6, it places them in `${PREFIX}/include`, but also places symlinks to them in `${PREFIX}/include/ncursues` and `${PREFIX}/include/ncursuesw`. If we can reproduce that behavior, that would be ideal I think. That way applications expecting to find them in `${PREFIX}/include/ncursues` and `${PREFIX}/include/ncursuesw` can find them, but they are also available in `${PREFIX}/include` for those that prefer to find them there. Note that symlinking widec and and non-widec includes to the same includes is ok because they are [source compatible]( http://www.linuxfromscratch.org/lfs/view/6.5/chapter06/ncurses.html ).

**Comment by jakirkham** [comment] 2016-04-16 18:22
I have implemented the strategy mentioned above in this PR ( https://github.com/conda-forge/ncurses-feedstock/pull/8 ). If you guys would like to take a look, I would appreciate your feedback.

**Closed** 2016-04-16 23:38 UTC
